# Generated by Django 5.0.3 on 2024-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser", name="age", field=models.IntegerField(default=0),
        ),
    ]
