# Generated by Django 5.0.3 on 2024-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
