# Generated by Django 5.0.3 on 2024-03-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
    ]
