# Generated by Django 5.0.3 on 2024-03-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_first_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
